# Generated by Django 4.0.6 on 2023-01-30 05:08

from django.db import migrations, models
import django.db.models.deletion
import refresher_course.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Kurs nomi')),
                ('description', models.TextField(null=True, verbose_name='Text')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('key', models.CharField(default='uz', max_length=3)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Millat',
                'verbose_name_plural': 'Millatlar',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.PositiveBigIntegerField(default=5, unique=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='CourseComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(blank=True, max_length=3, null=True, verbose_name='Kurs boshlangan kun')),
                ('end_date', models.CharField(blank=True, max_length=3, null=True, verbose_name='Kurs tugagan kun')),
                ('month', models.CharField(choices=[('yanvar', 'Yanvar'), ('fevral', 'Fevral'), ('mart', 'Mart'), ('aprel', 'Aprel'), ('may', 'May'), ('iyun', 'Iyun'), ('iyul', 'Iyul'), ('avgust', 'Avgust'), ('sentabr', 'Sentabr'), ('oktabr', 'Oktabr'), ('dekabr', 'Dekabr')], default='yanvar', max_length=50, verbose_name='Oy')),
                ('begin_cer_nomer', models.BigIntegerField(default=0, null=True, verbose_name="Boshlang'ich raqam")),
                ('file', models.FileField(max_length=255, upload_to=refresher_course.models.user_directory_path, verbose_name='Fayl')),
                ('year', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2022', max_length=4, verbose_name='Yil')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refresher_course.course')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refresher_course.nation')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiya')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism')),
                ('middle_name', models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='Otasini ismi')),
                ('start_date', models.CharField(blank=True, max_length=3, null=True, verbose_name='Kurs boshlangan kun')),
                ('end_date', models.CharField(blank=True, max_length=3, null=True, verbose_name='Kurs tugagan kun')),
                ('month', models.CharField(choices=[('yanvar', 'Yanvar'), ('fevral', 'Fevral'), ('mart', 'Mart'), ('aprel', 'Aprel'), ('may', 'May'), ('iyun', 'Iyun'), ('iyul', 'Iyul'), ('avgust', 'Avgust'), ('sentabr', 'Sentabr'), ('oktabr', 'Oktabr'), ('dekabr', 'Dekabr')], default='yanvar', max_length=50, verbose_name='Oy')),
                ('year', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2022', max_length=4, verbose_name='Yil')),
                ('cer_nomer', models.BigIntegerField(default=0, null=True, verbose_name='Sertifikat raqami')),
                ('qr_code', models.ImageField(default='qe.png', upload_to='qr_codes/', verbose_name='QR Code')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('passport', models.CharField(blank=True, default='-', max_length=15, null=True, verbose_name='Pasport')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refresher_course.course')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refresher_course.nation')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-id'],
            },
        ),
    ]
