# Generated by Django 4.0.6 on 2023-01-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refresher_course', '0004_alter_coursecomplete_month_alter_coursecomplete_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='registered_number',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Registratsiya nomeri'),
        ),
    ]
