# Generated by Django 4.0.6 on 2023-01-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refresher_course', '0006_certificate_created_at_certificate_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='registered_day',
            field=models.DateField(blank=True, null=True, verbose_name='Registeratsiya kuni'),
        ),
    ]
