# Generated by Django 4.0.6 on 2023-01-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refresher_course', '0007_certificate_registered_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='registered_day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registeratsiya sanasi'),
        ),
    ]
