# Generated by Django 4.0.6 on 2023-01-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refresher_course', '0009_alter_certificate_registered_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Sertifikat', 'verbose_name_plural': 'Sertifikatlar'},
        ),
    ]
