# Generated by Django 4.0.6 on 2023-01-30 14:33

import django.core.validators
from django.db import migrations, models
import refresher_course.models


class Migration(migrations.Migration):

    dependencies = [
        ('refresher_course', '0010_alter_certificate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomplete',
            name='file',
            field=models.FileField(max_length=255, upload_to=refresher_course.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.xlsx'])], verbose_name='Fayl'),
        ),
    ]
