# Generated by Django 4.0.6 on 2023-01-30 15:01

import django.core.validators
from django.db import migrations, models
import refresher_course.models


class Migration(migrations.Migration):

    dependencies = [
        ('refresher_course', '0011_alter_coursecomplete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomplete',
            name='file',
            field=models.FileField(upload_to=refresher_course.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.xlsx', '.xls'])], verbose_name='Fayl'),
        ),
    ]
