# Generated by Django 4.0.6 on 2023-02-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refresher_course', '0012_alter_coursecomplete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomplete',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], default='2023', max_length=4, verbose_name='Yil'),
        ),
    ]
