# Generated by Django 4.0.6 on 2023-02-13 06:08

from django.db import migrations, models
import refresher_course.models


class Migration(migrations.Migration):

    dependencies = [
        ('refresher_course', '0013_alter_coursecomplete_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], default='2023', max_length=4, verbose_name='Yil'),
        ),
        migrations.AlterField(
            model_name='coursecomplete',
            name='file',
            field=models.FileField(upload_to=refresher_course.models.user_directory_path, verbose_name='Fayl'),
        ),
    ]
