# Generated by Django 4.0.6 on 2023-02-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refresher_course', '0014_alter_certificate_year_alter_coursecomplete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hour_course',
            field=models.IntegerField(default=0),
        ),
    ]
