# Generated by Django 4.0.6 on 2023-02-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refresher_course', '0015_course_hour_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_visible_hour',
            field=models.BooleanField(default=False),
        ),
    ]
