# Generated by Django 4.0.6 on 2023-02-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refresher_course', '0017_certificate_invoice_certificate_jshshr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='invoice',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='jshshr',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Jshshr'),
        ),
    ]
